In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
# https://www.kaggle.com/mlg-ulb/creditcardfraud

In [7]:
df = pd.read_csv("data/creditcard.csv")

In [8]:
df.shape

(284807, 31)

In [9]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [10]:
df.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [13]:
df.describe().loc[['min', 'max', 'mean']]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000
mean,94813.859575,3.919560e-15,5.688174e-16,-8.769071e-15,2.782312e-15,-1.552563e-15,2.010663e-15,-1.694249e-15,-1.927028e-16,-3.137024e-15,...,1.537294e-16,7.959909e-16,5.367590e-16,4.458112e-15,1.453003e-15,1.699104e-15,-3.660161e-16,-1.206049e-16,88.349619,0.001727

In [10]:
df.sample(100)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
166126,117878.0,-0.913903,1.127020,1.496179,-0.554453,0.043367,0.193685,0.144181,0.535229,-0.196712,...,-0.154099,-0.521407,-0.221906,0.457950,0.411920,-0.433566,-0.048758,0.018775,5.00,0
183190,125692.0,1.923734,0.376890,-1.001153,3.501455,0.772925,0.736075,-0.052467,0.163876,-0.938645,...,0.289562,0.823409,-0.040413,0.181434,0.244067,0.226039,-0.049845,-0.061985,10.59,0
68782,53138.0,-0.743171,0.437490,0.941137,-1.386852,1.060519,0.419298,1.007224,0.118144,-0.953770,...,-0.427984,-1.534951,0.072999,-1.343376,0.198953,0.528577,-0.158187,-0.053871,86.45,0
279208,168708.0,2.045002,-0.149993,-1.199608,0.224479,0.030258,-0.706114,0.033053,-0.131986,0.395122,...,-0.267589,-0.698083,0.293037,-0.377540,-0.302144,0.201938,-0.078698,-0.075040,0.89,0
202824,134506.0,1.940095,-0.409976,-0.338015,0.304451,-0.457060,0.122076,-0.705851,0.132950,1.079899,...,0.250942,0.942871,0.137825,0.808974,-0.087392,-0.271590,0.037960,-0.037388,9.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113978,73284.0,-2.713520,1.930577,0.965943,-0.239390,-0.836476,0.770832,-0.620868,0.587514,1.135387,...,0.378835,0.271508,-0.009663,-0.345602,-0.262079,-0.795296,-2.404595,-0.337202,12.99,0
235504,148413.0,0.546696,0.988024,-0.508110,1.898059,0.843531,-0.123851,0.882562,-0.110630,-0.811310,...,0.241464,0.953916,-0.129870,-0.462743,-0.994137,-0.239367,0.331168,0.261145,1.00,0
166813,118325.0,2.108835,-0.180044,-1.864584,-0.100775,0.676780,0.006069,-0.037031,-0.024490,0.578392,...,0.225034,0.699221,-0.100568,-0.338760,0.354147,-0.085788,-0.032867,-0.073199,3.59,0
184672,126334.0,-0.351559,-0.123771,1.380560,-1.612284,-0.081382,0.022792,-0.118699,0.199053,-1.210100,...,-0.462526,-0.978734,0.239355,0.711334,-0.949582,0.119603,0.125861,0.178216,16.98,0
253641,156342.0,1.734559,-0.788260,-0.618628,0.074054,-0.587416,-0.230648,-0.359174,0.030542,0.996481,...,-0.127243,-0.535908,0.251065,-0.419604,-0.555233,-0.335078,-0.019300,-0.028907,132.00,0